USE [master]
GO

CREATE DATABASE [PropertiesUS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PropertiesUS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PropertiesUS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PropertiesUS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PropertiesUS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PropertiesUS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PropertiesUS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PropertiesUS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PropertiesUS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PropertiesUS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PropertiesUS] SET ARITHABORT OFF 
GO

ALTER DATABASE [PropertiesUS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PropertiesUS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PropertiesUS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PropertiesUS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PropertiesUS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PropertiesUS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PropertiesUS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PropertiesUS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PropertiesUS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PropertiesUS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PropertiesUS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PropertiesUS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PropertiesUS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PropertiesUS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PropertiesUS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PropertiesUS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PropertiesUS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PropertiesUS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PropertiesUS] SET  MULTI_USER 
GO

ALTER DATABASE [PropertiesUS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PropertiesUS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PropertiesUS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PropertiesUS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PropertiesUS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PropertiesUS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PropertiesUS] SET  READ_WRITE 
GO
